volumes:
    database:
        driver: "local"

networks:
    app:

services:
    database:
        image: "mysql:8.2"
        restart: "always"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5
        environment:
            TZ: "UTC"
            MYSQL_ROOT_PASSWORD: "root" # ADJUST
            MYSQL_DATABASE: "opencoursematch" # ADJUST
            MYSQL_USER: "opencoursematch" # ADJUST
            MYSQL_PASSWORD: "opencoursematch" # ADJUST
        volumes:
            - "database:/var/lib/mysql"
        networks:
            - "app"

    app:
        image: "ghcr.io/opencoursematch/opencoursematch:latest" # ADJUST
        restart: "always"
        depends_on:
            database:
                condition: service_healthy
        environment:
            TZ: "UTC"
        volumes:
            - "./config:/app/config"
            - "./app-logs:/app/logs"
            - "./app-files:/app/files"
        ports:
            - "80:80"
        networks:
            - "app"

    backup:
        image: "ghcr.io/struktal/mysql-backup:latest"
        restart: "always"
        environment:
            TZ: "UTC"
            DB_HOST: "database"
            DB_USER: "opencoursematch" # ADJUST
            DB_PASS: "opencoursematch" # ADJUST
            DB_DATABASE: "opencoursematch" # ADJUST
        volumes:
            - "./database-backup:/backup"
