FROM alpine:latest

# Update package manager
RUN apk update && apk upgrade
RUN apk --no-cache add tzdata

# Install nginx, PHP, composer, nodejs and npm
RUN apk --no-cache add nginx php84 php84-fpm php84-phar composer nodejs npm git

# Install PHP packages
RUN apk --no-cache add php84-session php84-tokenizer php84-mysqli php84-pdo php84-pdo_mysql php84-curl php84-gd php84-intl php84-mbstring php84-iconv php84-xml php84-simplexml php84-xmlwriter php84-dom php84-ctype php84-apcu

# Set working directory
WORKDIR /app
RUN chown -R nginx:nginx /app

# Copy application files
COPY --chown=nginx:nginx . .
COPY --chown=nginx:nginx ./docker/nodejs .
COPY --chown=nginx:nginx ./docker/nginx-config /etc/nginx
COPY --chown=nginx:nginx ./docker/php-fpm-config /etc/php84/php-fpm.d
COPY --chown=nginx:nginx ./docker/entrypoint-dev.sh .

# Adjust permissions
RUN mkdir -p logs && chown -R nginx:nginx logs && \
    mkdir -p files && chown -R nginx:nginx files && \
    mkdir -p template-cache && chown -R nginx:nginx template-cache && \
    chmod 777 /app/logs && \
    chmod 777 /app/files && \
    chmod 777 /app/template-cache && \
    chmod +x /app/entrypoint-dev.sh

# Link src/static to public/static
RUN rm -rf /app/public/static && ln -s /app/src/static /app/public/static

# Install composer dependencies
RUN php84 $(which composer).phar install --no-dev --no-interaction

# Install npm dependencies
RUN npm install

# Build tailwindcss
RUN npx @tailwindcss/cli --input src/static/css/base.css --output src/static/css/style.css --minify

# Setup crontab
RUN crontab -u nginx /app/src/cronjobs/.crontab

EXPOSE 80
ENTRYPOINT ["/app/entrypoint-dev.sh"]
